name: Continuous Integration

on: [push]

env:
  CI: true
  FORCE_COLOR: '1' # https://github.com/chalk/chalk/issues/203

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: build and test
        env:
          NODE_ICU_DATA: './node_modules/full-icu' # needed only for Node.js 12 (default from 14+)
        run: |
          yarn run flow
          yarn run lint
          yarn run test
