name: Continuous Integration

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    # TODO: lint
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn run flow
          yarn run export
