version = 1

[merge]
automerge_label = ["automerge", "automerge priority"]
priority_merge_label = "automerge priority"
require_automerge_label = true
method = "rebase"
delete_branch_on_merge = true

# TODO: consider `approve.auto_approve_usernames` for Dependabot
#  see: https://kodiakhq.com/docs/recipes#adding-pull-request-approvals-to-dependabot-pull-requests
