# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

# Note: we are using Renovate for most of the dependency updates (see `renovate.json5`)
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/src/sx-tailwind-website/__github__/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
