// @flow strict

// https://jestjs.io/docs/en/configuration
module.exports = {
  displayName: 'lint',
  rootDir: __dirname,
  verbose: false,
  reporters: ['@adeira/eslint-runner/reporter'],
  runner: '@adeira/eslint-runner',
  testMatch: ['<rootDir>/src/**/*.js', '<rootDir>/scripts/**/*.js'],
  testPathIgnorePatterns: [
    '/node_modules/',

    // The only reason why this is here is because Jest fails on unrelated .snap files generated by Rust Insta.
    // See: https://github.com/facebook/jest/issues/8922
    '<rootDir>/src/ya-comiste-rust/',
  ],
};
