changesetIgnorePatterns:
  - "**/*.test.js"
  - "**/Dockerfile"
  - "**/package.json"
  - "**/yarn.lock"

nodeLinker: node-modules

plugins:
  - .yarn/plugins/plugin-monorepo-scanner.js

yarnPath: .yarn/releases/yarn-4.0.1.cjs
