nodeLinker: node-modules

plugins:
  - .yarn/plugins/plugin-monorepo-scanner.js
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

changesetIgnorePatterns:
  - "**/*.test.js"
  - "**/Dockerfile"
  - "**/package.json"
  - "**/yarn.lock"
