/**
 * @generated SignedSource<<496f814dcf1d63f2436abf265c72803f>>
 * @flow strict
 *
 * @see https://www.w3.org/Style/CSS/all-properties.en.html
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units
 */

export type AllCSSPropertyTypes = {|
  +alignContent?:
    | 'center'
    | 'start'
    | 'end'
    | 'flex-start'
    | 'flex-end'
    | 'normal'
    | 'baseline'
    | 'first baseline'
    | 'last baseline'
    | 'space-between'
    | 'space-around'
    | 'space-evenly'
    | 'stretch'
    | 'safe center'
    | 'unsafe center'
    | 'inherit'
    | 'initial'
    | 'unset',
  +alignItems?:
    | 'normal'
    | 'stretch'
    | 'center'
    | 'start'
    | 'end'
    | 'flex-start'
    | 'flex-end'
    | 'baseline'
    | 'first baseline'
    | 'last baseline'
    | 'safe center'
    | 'unsafe center'
    | 'inherit'
    | 'initial'
    | 'unset',
  +alignSelf?:
    | 'auto'
    | 'normal'
    | 'center'
    | 'start'
    | 'end'
    | 'self-start'
    | 'self-end'
    | 'flex-start'
    | 'flex-end'
    | 'baseline'
    | 'first baseline'
    | 'last baseline'
    | 'stretch'
    | 'safe center'
    | 'unsafe center'
    | 'inherit'
    | 'initial'
    | 'unset',
  +alignmentBaseline?: string | number,
  +all?: string | number,
  +animation?: string | number,
  +animationDelay?: string | number,
  +animationDirection?: string | number,
  +animationDuration?: string | number,
  +animationFillMode?: string | number,
  +animationIterationCount?: string | number,
  +animationName?: string | number,
  +animationPlayState?: string | number,
  +animationTimingFunction?: string | number,
  +appearance?: string | number,
  +aspectRatio?: string | number,
  +azimuth?: string | number,
  +backfaceVisibility?: string | number,
  +background?: string | number,
  +backgroundAttachment?: string | number,
  +backgroundBlendMode?: string | number,
  +backgroundClip?: string | number,
  +backgroundColor?: string | number,
  +backgroundImage?: string | number,
  +backgroundOrigin?: string | number,
  +backgroundPosition?: string | number,
  +backgroundRepeat?: string | number,
  +backgroundSize?: string | number,
  +baselineShift?: string | number,
  +baselineSource?: string | number,
  +blockEllipsis?: string | number,
  +blockSize?: string | number,
  +blockStep?: string | number,
  +blockStepAlign?: string | number,
  +blockStepInsert?: string | number,
  +blockStepRound?: string | number,
  +blockStepSize?: string | number,
  +bookmarkLabel?: string | number,
  +bookmarkLevel?: string | number,
  +bookmarkState?: string | number,
  +border?: string | number,
  +borderBlock?: string | number,
  +borderBlockColor?: string | number,
  +borderBlockEnd?: string | number,
  +borderBlockEndColor?: string | number,
  +borderBlockEndStyle?: string | number,
  +borderBlockEndWidth?: string | number,
  +borderBlockStart?: string | number,
  +borderBlockStartColor?: string | number,
  +borderBlockStartStyle?: string | number,
  +borderBlockStartWidth?: string | number,
  +borderBlockStyle?: string | number,
  +borderBlockWidth?: string | number,
  +borderBottom?: string | number,
  +borderBottomColor?: string | number,
  +borderBottomLeftRadius?: string | number,
  +borderBottomRightRadius?: string | number,
  +borderBottomStyle?: string | number,
  +borderBottomWidth?: string | number,
  +borderBoundary?: string | number,
  +borderCollapse?: string | number,
  +borderColor?: string | number,
  +borderEndEndRadius?: string | number,
  +borderEndStartRadius?: string | number,
  +borderImage?: string | number,
  +borderImageOutset?: string | number,
  +borderImageRepeat?: string | number,
  +borderImageSlice?: string | number,
  +borderImageSource?: string | number,
  +borderImageWidth?: string | number,
  +borderInline?: string | number,
  +borderInlineColor?: string | number,
  +borderInlineEnd?: string | number,
  +borderInlineEndColor?: string | number,
  +borderInlineEndStyle?: string | number,
  +borderInlineEndWidth?: string | number,
  +borderInlineStart?: string | number,
  +borderInlineStartColor?: string | number,
  +borderInlineStartStyle?: string | number,
  +borderInlineStartWidth?: string | number,
  +borderInlineStyle?: string | number,
  +borderInlineWidth?: string | number,
  +borderLeft?: string | number,
  +borderLeftColor?: string | number,
  +borderLeftStyle?: string | number,
  +borderLeftWidth?: string | number,
  +borderRadius?: string | number,
  +borderRight?: string | number,
  +borderRightColor?: string | number,
  +borderRightStyle?: string | number,
  +borderRightWidth?: string | number,
  +borderSpacing?: string | number,
  +borderStartEndRadius?: string | number,
  +borderStartStartRadius?: string | number,
  +borderStyle?: string | number,
  +borderTop?: string | number,
  +borderTopColor?: string | number,
  +borderTopLeftRadius?: string | number,
  +borderTopRightRadius?: string | number,
  +borderTopStyle?: string | number,
  +borderTopWidth?: string | number,
  +borderWidth?: string | number,
  +bottom?: string | number,
  +boxDecorationBreak?: string | number,
  +boxShadow?: string | number,
  +boxSizing?: string | number,
  +boxSnap?: string | number,
  +breakAfter?: string | number,
  +breakBefore?: string | number,
  +breakInside?: string | number,
  +captionSide?: string | number,
  +caret?: string | number,
  +caretColor?: string | number,
  +caretShape?: string | number,
  +chains?: string | number,
  +clear?: string | number,
  +clip?: string | number,
  +clipPath?: string | number,
  +clipRule?: string | number,
  +color?: string | number,
  +colorAdjust?: string | number,
  +colorInterpolationFilters?: string | number,
  +colorScheme?: string | number,
  +columnCount?: string | number,
  +columnFill?: string | number,
  +columnGap?: string | number,
  +columnRule?: string | number,
  +columnRuleColor?: string | number,
  +columnRuleStyle?: string | number,
  +columnRuleWidth?: string | number,
  +columnSpan?: string | number,
  +columnWidth?: string | number,
  +columns?: string | number,
  +contain?: string | number,
  +containIntrinsicSize?: string | number,
  +content?: string | number,
  +contentVisibility?: string | number,
  +continue?: string | number,
  +counterIncrement?: string | number,
  +counterReset?: string | number,
  +counterSet?: string | number,
  +cue?: string | number,
  +cueAfter?: string | number,
  +cueBefore?: string | number,
  +cursor?: string | number,
  +direction?: string | number,
  +display?:
    | 'block'
    | 'inline'
    | 'run-in'
    | 'flow'
    | 'flow-root'
    | 'table'
    | 'flex'
    | 'grid'
    | 'ruby'
    | 'table-row-group'
    | 'table-header-group'
    | 'table-footer-group'
    | 'table-row'
    | 'table-cell'
    | 'table-column-group'
    | 'table-column'
    | 'table-caption'
    | 'ruby-base'
    | 'ruby-text'
    | 'ruby-base-container'
    | 'contents'
    | 'none'
    | 'inline-block'
    | 'inline-list-item'
    | 'inline-table'
    | 'inline-flex'
    | 'inline-grid',
  +dominantBaseline?: string | number,
  +elevation?: string | number,
  +emptyCells?: string | number,
  +fill?: string | number,
  +fillBreak?: string | number,
  +fillColor?: string | number,
  +fillImage?: string | number,
  +fillOpacity?: string | number,
  +fillOrigin?: string | number,
  +fillPosition?: string | number,
  +fillRepeat?: string | number,
  +fillRule?: string | number,
  +fillSize?: string | number,
  +filter?: string | number,
  +flex?: string | number,
  +flexBasis?: string | number,
  +flexDirection?:
    | 'row'
    | 'row-reverse'
    | 'column'
    | 'column-reverse'
    | 'inherit'
    | 'initial'
    | 'unset',
  +flexFlow?:
    | 'row'
    | 'row-reverse'
    | 'column'
    | 'column-reverse'
    | 'nowrap'
    | 'wrap'
    | 'wrap-reverse'
    | 'row nowrap'
    | 'column wrap'
    | 'column-reverse wrap-reverse'
    | 'inherit'
    | 'initial'
    | 'unset',
  +flexGrow?: string | number,
  +flexShrink?: string | number,
  +flexWrap?: 'nowrap' | 'wrap' | 'wrap-reverse' | 'inherit' | 'initial' | 'unset',
  +float?: string | number,
  +floatDefer?: string | number,
  +floatOffset?: string | number,
  +floatReference?: string | number,
  +floodColor?: string | number,
  +floodOpacity?: string | number,
  +flow?: string | number,
  +flowFrom?: string | number,
  +flowInto?: string | number,
  +font?: string | number,
  +fontFamily?: string | number,
  +fontFeatureSettings?: string | number,
  +fontKerning?: string | number,
  +fontLanguageOverride?: string | number,
  +fontOpticalSizing?: string | number,
  +fontPalette?: string | number,
  +fontSize?: string | number,
  +fontSizeAdjust?: string | number,
  +fontStretch?: string | number,
  +fontStyle?: string | number,
  +fontSynthesis?: string | number,
  +fontSynthesisSmallCaps?: string | number,
  +fontSynthesisStyle?: string | number,
  +fontSynthesisWeight?: string | number,
  +fontVariant?: string | number,
  +fontVariantAlternates?: string | number,
  +fontVariantCaps?: string | number,
  +fontVariantEastAsian?: string | number,
  +fontVariantEmoji?: string | number,
  +fontVariantLigatures?: string | number,
  +fontVariantNumeric?: string | number,
  +fontVariantPosition?: string | number,
  +fontVariationSettings?: string | number,
  +fontWeight?: string | number,
  +footnoteDisplay?: string | number,
  +footnotePolicy?: string | number,
  +forcedColorAdjust?: string | number,
  +gap?: string | number,
  +glyphOrientationVertical?: string | number,
  +grid?: string | number,
  +gridArea?: string | number,
  +gridAutoColumns?: string | number,
  +gridAutoFlow?: string | number,
  +gridAutoRows?: string | number,
  +gridColumn?: string | number,
  +gridColumnEnd?: string | number,
  +gridColumnStart?: string | number,
  +gridRow?: string | number,
  +gridRowEnd?: string | number,
  +gridRowStart?: string | number,
  +gridTemplate?: string | number,
  +gridTemplateAreas?: string | number,
  +gridTemplateColumns?: string | number,
  +gridTemplateRows?: string | number,
  +hangingPunctuation?: string | number,
  +height?: string | number,
  +hyphenateCharacter?: string | number,
  +hyphenateLimitChars?: string | number,
  +hyphenateLimitLast?: string | number,
  +hyphenateLimitLines?: string | number,
  +hyphenateLimitZone?: string | number,
  +hyphens?: string | number,
  +imageOrientation?: string | number,
  +imageRendering?: string | number,
  +imageResolution?: string | number,
  +initialLetter?: string | number,
  +initialLetterAlign?: string | number,
  +initialLetterWrap?: string | number,
  +inlineSize?: string | number,
  +inlineSizing?: string | number,
  +inset?: string | number,
  +insetBlock?: string | number,
  +insetBlockEnd?: string | number,
  +insetBlockStart?: string | number,
  +insetInline?: string | number,
  +insetInlineEnd?: string | number,
  +insetInlineStart?: string | number,
  +isolation?: string | number,
  +justifyContent?: string | number,
  +justifyItems?: string | number,
  +justifySelf?: string | number,
  +leadingTrim?: string | number,
  +left?: string | number,
  +letterSpacing?: string | number,
  +lightingColor?: string | number,
  +lineBreak?: string | number,
  +lineClamp?: string | number,
  +lineGrid?: string | number,
  +lineHeight?: string | number,
  +lineHeightStep?: string | number,
  +linePadding?: string | number,
  +lineSnap?: string | number,
  +listStyle?: string | number,
  +listStyleImage?: string | number,
  +listStylePosition?: string | number,
  +listStyleType?: string | number,
  +margin?: string | number,
  +marginBlock?: string | number,
  +marginBlockEnd?: string | number,
  +marginBlockStart?: string | number,
  +marginBottom?: string | number,
  +marginBreak?: string | number,
  +marginInline?: string | number,
  +marginInlineEnd?: string | number,
  +marginInlineStart?: string | number,
  +marginLeft?: string | number,
  +marginRight?: string | number,
  +marginTop?: string | number,
  +marginTrim?: string | number,
  +marker?: string | number,
  +markerEnd?: string | number,
  +markerKnockoutLeft?: string | number,
  +markerKnockoutRight?: string | number,
  +markerMid?: string | number,
  +markerPattern?: string | number,
  +markerSegment?: string | number,
  +markerSide?: string | number,
  +markerStart?: string | number,
  +mask?: string | number,
  +maskBorder?: string | number,
  +maskBorderMode?: string | number,
  +maskBorderOutset?: string | number,
  +maskBorderRepeat?: string | number,
  +maskBorderSlice?: string | number,
  +maskBorderSource?: string | number,
  +maskBorderWidth?: string | number,
  +maskClip?: string | number,
  +maskComposite?: string | number,
  +maskImage?: string | number,
  +maskMode?: string | number,
  +maskOrigin?: string | number,
  +maskPosition?: string | number,
  +maskRepeat?: string | number,
  +maskSize?: string | number,
  +maskType?: string | number,
  +maxBlockSize?: string | number,
  +maxHeight?: string | number,
  +maxInlineSize?: string | number,
  +maxLines?: string | number,
  +maxWidth?: string | number,
  +minBlockSize?: string | number,
  +minHeight?: string | number,
  +minInlineSize?: string | number,
  +minWidth?: string | number,
  +mixBlendMode?: string | number,
  +navDown?: string | number,
  +navLeft?: string | number,
  +navRight?: string | number,
  +navUp?: string | number,
  +objectFit?: string | number,
  +objectPosition?: string | number,
  +offset?: string | number,
  +offsetAnchor?: string | number,
  +offsetDistance?: string | number,
  +offsetPath?: string | number,
  +offsetPosition?: string | number,
  +offsetRotate?: string | number,
  +opacity?: string | number,
  +order?: string | number,
  +orphans?: string | number,
  +outline?: string | number,
  +outlineColor?: string | number,
  +outlineOffset?: string | number,
  +outlineStyle?: string | number,
  +outlineWidth?: string | number,
  +overflow?: string | number,
  +overflowAnchor?: string | number,
  +overflowBlock?: string | number,
  +overflowClipMargin?: string | number,
  +overflowInline?: string | number,
  +overflowWrap?: string | number,
  +overflowX?: string | number,
  +overflowY?: string | number,
  +overscrollBehavior?: string | number,
  +overscrollBehaviorBlock?: string | number,
  +overscrollBehaviorInline?: string | number,
  +overscrollBehaviorX?: string | number,
  +overscrollBehaviorY?: string | number,
  +padding?: string | number,
  +paddingBlock?: string | number,
  +paddingBlockEnd?: string | number,
  +paddingBlockStart?: string | number,
  +paddingBottom?: string | number,
  +paddingInline?: string | number,
  +paddingInlineEnd?: string | number,
  +paddingInlineStart?: string | number,
  +paddingLeft?: string | number,
  +paddingRight?: string | number,
  +paddingTop?: string | number,
  +page?: string | number,
  +pageBreakAfter?: string | number,
  +pageBreakBefore?: string | number,
  +pageBreakInside?: string | number,
  +pause?: string | number,
  +pauseAfter?: string | number,
  +pauseBefore?: string | number,
  +perspective?: string | number,
  +perspectiveOrigin?: string | number,
  +pitch?: string | number,
  +pitchRange?: string | number,
  +placeContent?: string | number,
  +placeItems?: string | number,
  +placeSelf?: string | number,
  +playDuring?: string | number,
  +position?: string | number,
  +propertyName?: string | number,
  +quotes?: string | number,
  +regionFragment?: string | number,
  +resize?: string | number,
  +rest?: string | number,
  +restAfter?: string | number,
  +restBefore?: string | number,
  +richness?: string | number,
  +right?: string | number,
  +rotate?: string | number,
  +rowGap?: string | number,
  +rubyAlign?: string | number,
  +rubyMerge?: string | number,
  +rubyOverhang?: string | number,
  +rubyPosition?: string | number,
  +running?: string | number,
  +scale?: string | number,
  +scrollBehavior?: string | number,
  +scrollMargin?: string | number,
  +scrollMarginBlock?: string | number,
  +scrollMarginBlockEnd?: string | number,
  +scrollMarginBlockStart?: string | number,
  +scrollMarginBottom?: string | number,
  +scrollMarginInline?: string | number,
  +scrollMarginInlineEnd?: string | number,
  +scrollMarginInlineStart?: string | number,
  +scrollMarginLeft?: string | number,
  +scrollMarginRight?: string | number,
  +scrollMarginTop?: string | number,
  +scrollPadding?: string | number,
  +scrollPaddingBlock?: string | number,
  +scrollPaddingBlockEnd?: string | number,
  +scrollPaddingBlockStart?: string | number,
  +scrollPaddingBottom?: string | number,
  +scrollPaddingInline?: string | number,
  +scrollPaddingInlineEnd?: string | number,
  +scrollPaddingInlineStart?: string | number,
  +scrollPaddingLeft?: string | number,
  +scrollPaddingRight?: string | number,
  +scrollPaddingTop?: string | number,
  +scrollSnapAlign?: string | number,
  +scrollSnapStop?: string | number,
  +scrollSnapType?: string | number,
  +scrollbarColor?: string | number,
  +scrollbarGutter?: string | number,
  +scrollbarWidth?: string | number,
  +shapeImageThreshold?: string | number,
  +shapeInside?: string | number,
  +shapeMargin?: string | number,
  +shapeOutside?: string | number,
  +spatialNavigationAction?: string | number,
  +spatialNavigationContain?: string | number,
  +spatialNavigationFunction?: string | number,
  +speak?: string | number,
  +speakAs?: string | number,
  +speakHeader?: string | number,
  +speakNumeral?: string | number,
  +speakPunctuation?: string | number,
  +speechRate?: string | number,
  +stress?: string | number,
  +stringSet?: string | number,
  +stroke?: string | number,
  +strokeAlign?: string | number,
  +strokeAlignment?: string | number,
  +strokeBreak?: string | number,
  +strokeColor?: string | number,
  +strokeDashCorner?: string | number,
  +strokeDashJustify?: string | number,
  +strokeDashadjust?: string | number,
  +strokeDasharray?: string | number,
  +strokeDashcorner?: string | number,
  +strokeDashoffset?: string | number,
  +strokeImage?: string | number,
  +strokeLinecap?: string | number,
  +strokeLinejoin?: string | number,
  +strokeMiterlimit?: string | number,
  +strokeOpacity?: string | number,
  +strokeOrigin?: string | number,
  +strokePosition?: string | number,
  +strokeRepeat?: string | number,
  +strokeSize?: string | number,
  +strokeWidth?: string | number,
  +tabSize?: string | number,
  +tableLayout?: string | number,
  +textAlign?: string | number,
  +textAlignAll?: string | number,
  +textAlignLast?: string | number,
  +textCombineUpright?: string | number,
  +textDecoration?: string | number,
  +textDecorationColor?: string | number,
  +textDecorationLine?: string | number,
  +textDecorationSkip?: string | number,
  +textDecorationSkipBox?: string | number,
  +textDecorationSkipInk?: string | number,
  +textDecorationSkipInset?: string | number,
  +textDecorationSkipSelf?: string | number,
  +textDecorationSkipSpaces?: string | number,
  +textDecorationStyle?: string | number,
  +textDecorationThickness?: string | number,
  +textEdge?: string | number,
  +textEmphasis?: string | number,
  +textEmphasisColor?: string | number,
  +textEmphasisPosition?: string | number,
  +textEmphasisSkip?: string | number,
  +textEmphasisStyle?: string | number,
  +textGroupAlign?: string | number,
  +textIndent?: string | number,
  +textJustify?: string | number,
  +textOrientation?: string | number,
  +textOverflow?: string | number,
  +textShadow?: string | number,
  +textSpaceCollapse?: string | number,
  +textSpaceTrim?: string | number,
  +textSpacing?: string | number,
  +textTransform?: string | number,
  +textUnderlineOffset?: string | number,
  +textUnderlinePosition?: string | number,
  +textWrap?: string | number,
  +top?: string | number,
  +transform?: string | number,
  +transformBox?: string | number,
  +transformOrigin?: string | number,
  +transformStyle?: string | number,
  +transition?: string | number,
  +transitionDelay?: string | number,
  +transitionDuration?: string | number,
  +transitionProperty?: string | number,
  +transitionTimingFunction?: string | number,
  +translate?: string | number,
  +unicodeBidi?: string | number,
  +userSelect?: string | number,
  +verticalAlign?: string | number,
  +visibility?: string | number,
  +voiceBalance?: string | number,
  +voiceDuration?: string | number,
  +voiceFamily?: string | number,
  +voicePitch?: string | number,
  +voiceRange?: string | number,
  +voiceRate?: string | number,
  +voiceStress?: string | number,
  +voiceVolume?: string | number,
  +volume?: string | number,
  +whiteSpace?: string | number,
  +widows?: string | number,
  +width?: string | number,
  +willChange?: string | number,
  +wordBoundaryDetection?: string | number,
  +wordBoundaryExpansion?: string | number,
  +wordBreak?: string | number,
  +wordSpacing?: string | number,
  +wordWrap?: string | number,
  +wrapAfter?: string | number,
  +wrapBefore?: string | number,
  +wrapFlow?: string | number,
  +wrapInside?: string | number,
  +wrapThrough?: string | number,
  +writingMode?: string | number,
  +zIndex?: number | 'auto' | 'inherit' | 'initial' | 'unset',
|};
