/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements
 */

import type { AllCSSPropertyTypes } from './AllCSSPropertyTypes';

export type AllCSSPseudoTypes = {
  +':active'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:active
  +':any-link'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:any-link
  +':checked'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:checked
  +':current'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:current
  +':blank'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:blank
  +':default'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:default
  +':defined'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:defined
  +':dir'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:dir
  +':disabled'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:disabled
  +':empty'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:empty
  +':enabled'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:enabled
  +':first'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:first
  +':first-child'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:first-child
  +':first-of-type'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:first-of-type
  +':fullscreen'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:fullscreen
  +':future'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:future
  +':focus'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:focus
  +':focus-visible'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:focus-visible
  +':focus-within'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:focus-within
  +':has'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:has
  +':hover'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:hover
  +':indeterminate'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:indeterminate
  +':in-range'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:in-range
  +':invalid'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:invalid
  +':is'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:is
  +':lang'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:lang
  +':last-child'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:last-child
  +':last-of-type'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:last-of-type
  +':link'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:link
  +':local-link'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:local-link
  +':not'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:not
  +':nth-child'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:nth-child
  +':nth-col'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:nth-col
  +':nth-last-child'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:nth-last-child
  +':nth-last-col'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:nth-last-col
  +':nth-last-of-type'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:nth-last-of-type
  +':nth-of-type'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:nth-of-type
  +':only-child'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:only-child
  +':only-of-type'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:only-of-type
  +':optional'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:optional
  +':out-of-range'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:out-of-range
  +':past'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:past
  +':paused'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:paused
  +':placeholder-shown'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:placeholder-shown
  +':playing'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:playing
  +':read-only'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:read-only
  +':read-write'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:read-write
  +':required'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:required
  +':scope'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:scope
  +':target'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:target
  +'::target-text'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::target-text
  +':target-within'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:target-within
  +':user-invalid'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:user-invalid
  +':user-valid'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:user-valid
  +':valid'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:valid
  +':visited'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:visited
  +':where'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:where
  +'::after'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::after
  +'::backdrop'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::backdrop
  +'::before'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::before
  +'::cue'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::cue
  +'::cue-region'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::cue-region
  +'::first-letter'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::first-letter
  +'::first-line'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::first-line
  +'::grammar-error'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::grammar-error
  +'::marker'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::marker
  +'::part'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::part
  +':picture-in-picture'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/:picture-in-picture
  +'::placeholder'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::placeholder
  +'::selection'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::selection
  +'::slotted'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::slotted
  +'::spelling-error'?: AllCSSPropertyTypes, // https://developer.mozilla.org/docs/Web/CSS/::spelling-error
};
