use crate::errors::ModelError;
use crate::graphql_context::Context;
use crate::model::sdui_sections::get_all_sections_for_entrypoint_key;
use crate::sdui_section::SDUISection;
use juniper::{EmptyMutation, EmptySubscription, FieldError, FieldResult, RootNode};

#[derive(Clone, Copy, Debug)]
pub struct Query;

#[juniper::graphql_object(context = Context)]
impl Query {
    async fn mobile_entrypoint_sections(
        key: String,
        context: &Context,
    ) -> FieldResult<Vec<SDUISection>> {
        let connection_pool = context.pool.to_owned();
        match get_all_sections_for_entrypoint_key(connection_pool, key).await {
            Ok(s) => Ok(s),
            // Err(e) => Err(FieldError::from(e)),
            Err(e) => match e {
                ModelError::DatabaseError(e) => Err(FieldError::from(e)), // TODO: hide and log these errors
                ModelError::LogicError(e) => Err(FieldError::from(e)),
            },
        }
    }
}

pub type Schema = RootNode<'static, Query, EmptyMutation<Context>, EmptySubscription<Context>>;

pub fn create_graphql_schema() -> Schema {
    Schema::new(
        Query,
        EmptyMutation::<Context>::new(),
        EmptySubscription::<Context>::new(),
    )
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::Path;

    #[test]
    fn schema_snapshot() {
        // This test will make sure that the schema generated by server is ready to be used by
        // clients. How to do it better?

        let new_schema_path = "./../../ya-comiste-meta/schema.graphql.new";
        let saved_schema_path = "./../../ya-comiste-meta/schema.graphql";
        let saved_schema_snapshot =
            fs::read_to_string(saved_schema_path).expect("unable to read schema file");

        assert!(signedsource::is_signed(&saved_schema_snapshot));
        assert!(signedsource::is_valid_signature(&saved_schema_snapshot));

        let new_schema_snapshot = signedsource::sign_file(&format!(
            "# {}\n\n{}",
            signedsource::SIGNING_TOKEN,
            super::create_graphql_schema().as_schema_language()
        ));

        if saved_schema_snapshot != new_schema_snapshot {
            fs::write(new_schema_path, new_schema_snapshot)
                .expect("unable to write new schema file");
        }

        assert_eq!(
            Path::new(new_schema_path).exists(),
            false,
            "schema snapshot with *.new extension should not exist - please resolve it"
        );
    }
}
