apiVersion: v1
kind: Service
metadata:
  name: abacus-service
spec:
  type: ClusterIP
  selector:
    app: abacus
  ports:
    # TODO: https (443)
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abacus-deployment
  labels:
    app: abacus
spec:
  replicas: 2
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: abacus
  template:
    metadata:
      labels:
        app: abacus
    spec:
      containers:
        - name: abacus
          image: adeira/abacus
          resources:
            # TODO: limits
            requests:
              cpu: 16m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /status/ping
              port: 5000
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: abacus-aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: abacus-aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: STRIPE_RESTRICTED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: abacus-stripe-secret
                  key: STRIPE_RESTRICTED_API_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: abacus-stripe-secret
                  key: STRIPE_WEBHOOK_SECRET
          args:
            - '--no-migrations'
            - '--arangodb-url=http://arangodb-single-server.default.svc.cluster.local:8529' # TODO: https://…
