# Get help on options with `rustfmt --help=config` (or https://rust-lang.github.io/rustfmt)
# Please keep these in alphabetical order.

edition = "2021"
use_field_init_shorthand = true
use_try_shorthand = true
