[package]
name = "signedsource"
edition = "2021"
version = "0.3.0"
authors = ["Facebook", "Martin Zlámal <mrtnzlml@gmail.com>"]
license = "MIT"
publish = ["crates-io"]
repository = "https://github.com/adeira/universe"
description = "Utility for signing and verifying generated files."
resolver = "2"

[dependencies]
hex = "0.4.3"
lazy_static = "1.4.0"
md-5 = "0.10.1"
regex = "1.5.5"
