/* eslint-disable flowtype/require-valid-file-annotation */

const FLOW_TYPE_NUMBER = Symbol.for('number');

export default new Map([
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/align-content
    'alignContent',
    [
      'center',
      'start',
      'end',
      'flex-start',
      'flex-end',
      'normal',
      'baseline',
      'first baseline',
      'last baseline',
      'space-between',
      'space-around',
      'space-evenly',
      'stretch',
      'safe center',
      'unsafe center',
      'inherit',
      'initial',
      'unset',
    ],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
    'alignItems',
    [
      'normal',
      'stretch',
      'center',
      'start',
      'end',
      'flex-start',
      'flex-end',
      'baseline',
      'first baseline',
      'last baseline',
      'safe center',
      'unsafe center',
      'inherit',
      'initial',
      'unset',
    ],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/align-self
    'alignSelf',
    [
      'auto',
      'normal',
      'center',
      'start',
      'end',
      'self-start',
      'self-end',
      'flex-start',
      'flex-end',
      'baseline',
      'first baseline',
      'last baseline',
      'stretch',
      'safe center',
      'unsafe center',
      'inherit',
      'initial',
      'unset',
    ],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/display
    'display',
    [
      'block',
      'inline',
      'run-in',
      'flow',
      'flow-root',
      'table',
      'flex',
      'grid',
      'ruby',
      'table-row-group',
      'table-header-group',
      'table-footer-group',
      'table-row',
      'table-cell',
      'table-column-group',
      'table-column',
      'table-caption',
      'ruby-base',
      'ruby-text',
      'ruby-base-container',
      'contents',
      'none',
      'inline-block',
      'inline-list-item',
      'inline-table',
      'inline-flex',
      'inline-grid',
    ],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction
    'flexDirection',
    ['row', 'row-reverse', 'column', 'column-reverse', 'inherit', 'initial', 'unset'],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow
    'flexFlow',
    [
      'row',
      'row-reverse',
      'column',
      'column-reverse',
      'nowrap',
      'wrap',
      'wrap-reverse',
      'row nowrap',
      'column wrap',
      'column-reverse wrap-reverse',
      'inherit',
      'initial',
      'unset',
    ],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap
    'flexWrap',
    ['nowrap', 'wrap', 'wrap-reverse', 'inherit', 'initial', 'unset'],
  ],
  [
    // https://developer.mozilla.org/en-US/docs/Web/CSS/z-index
    'zIndex',
    [FLOW_TYPE_NUMBER, 'auto', 'inherit', 'initial', 'unset'],
  ],
]);
