/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function Fingerprint(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <g
        fill="none"
        fillRule="evenodd"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M16.5 12.53c0 2.745-1.255 5.97-6 5.97a8.2 8.2 0 0 1-2.015-.232m-1.761-.781C5.034 16.317 4.5 14.32 4.5 12.53V8.5c0-1.566.655-2.98 1.705-3.981m1.672-1.354A5.5 5.5 0 0 1 10.5 2.5c1.753 0 3.493.723 4.5 2m1.206 1.22c.19.559.294 1.157.294 1.78v3" />
        <path d="M10.5 16.5q-2-1-2-2.97V8.5a2 2 0 1 1 4 0v4.03q0 1 1 1c1 0 1-.333 1-1V8.066a3 3 0 0 0-.304-1.316Q13.098 4.5 10.5 4.5T6.804 6.75A3 3 0 0 0 6.5 8.066V13.5q0 1.5.5 2" />
        <path d="M10.5 8.5v4.03q0 2.97 3 2.97" />
      </g>
    </svg>
  );
}
