/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function FlameAlt(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <path
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M10.5 3Q16 8 16 12.286c0 3.078-1.27 5.198-3.111 6.148.23-.491.361-1.092.361-1.791q0-2.143-2.75-4.643-2.75 2.5-2.75 4.643c0 .7.131 1.3.36 1.791-1.84-.95-3.11-3.07-3.11-6.148Q5 8 10.5 3"
      />
    </svg>
  );
}
