/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function Lineweight(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <g fill="none" fillRule="evenodd" stroke="currentColor">
        <rect width={14} height={2} x={3.5} y={6.5} fill="currentColor" rx={1} />
        <path fill="currentColor" d="M3.5 11.5h14v1h-14z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M3.5 15.5h13.981" />
      </g>
    </svg>
  );
}
