/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function Paperclip(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <path
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        d="m16.5 11.5-5 5q-3.781 4.144-7 1-3.22-3.145 1-7l5-5q2.878-3.122 5-1c2.122 2.122 1.08 3.08-1 5l-5 5Q8.082 16.082 7 15c-1.082-1.082-.555-1.555.5-2.5l5-5"
      />
    </svg>
  );
}
