/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function Reuse(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <g
        fill="none"
        fillRule="evenodd"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M3.5 2.5h5v5" />
        <path d="M8.5 2.5q-5 4.255-5 8.5t3 7.5m11 0h-5v-5" />
        <path d="M12.5 18.5q5-4.255 5-8.5t-3-7.5" />
      </g>
    </svg>
  );
}
