/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function Rocket(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <g
        fill="none"
        fillRule="evenodd"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        transform="translate(4 1)"
      >
        <path d="M6.5 18.5c3-2.502 4-5.502 4-9s-1-6.498-4-9c-3 2.502-4 5.502-4 9s1 6.498 4 9" />
        <path d="M10.062 13.362q.636.368 1.171.902 1.679 1.678 1.714 4.365c-2.509-.11-3.882-.765-4.926-1.647m-5.115-3.62a5.7 5.7 0 0 0-1.172.902Q.056 15.942.021 18.629c2.508-.11 3.882-.765 4.926-1.647" />
        <circle cx={6.5} cy={6.5} r={2} />
      </g>
    </svg>
  );
}
