/**
 * This file is automatically GENERATED.
 * Manual changes might be lost - proceed with caution!
 *
 * @flow strict
 */

import React, { type Element } from 'react';

type Props = {
  +'data-testid'?: string,
};

export default function Swap(props: Props): Element<'svg'> {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 21 21" {...props}>
      <g
        fill="none"
        fillRule="evenodd"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M13 8h5V3" />
        <path d="M18 8q-4.255-5-8.5-5T2 6m4.5 5.5h-5v5" />
        <path d="M1.5 11.5q4.255 5 8.5 5t7.5-3" />
      </g>
    </svg>
  );
}
