name: Continuous Integration

on: [push]

env:
  CI: true
  FORCE_COLOR: '1' # https://github.com/chalk/chalk/issues/203
  NODE_OPTIONS: --max-old-space-size=6144
  BABEL_DISABLE_CACHE: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn run typecheck
          yarn run lint
          yarn run test-only
          yarn workspace @adeira/example-relay test-bc
          yarn run scanner
