name: Continuous Integration (Rust)

on:
  push:
    paths:
      - 'src/ya-comiste-rust/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      # https://github.com/actions-rs/toolchain
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable

      # https://github.com/actions-rs/clippy-check
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path src/ya-comiste-rust/Cargo.toml

      # https://github.com/actions-rs/cargo
      - name: Run all tests
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --manifest-path src/ya-comiste-rust/Cargo.toml
