name: Continuous Integration (Rust)

on: [push]

jobs:
  build-all-targets:
    strategy:
      fail-fast: true
      matrix:
        manifest:
          - 'src/abacus/Cargo.toml'
          - 'src/signedsource-rs/Cargo.toml'
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin # 64-bit OSX (10.7+, Lion+)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu # 64-bit Linux (kernel 2.6.32+, glibc 2.11+)

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2.3.4

      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2.10.2
        id: paths-filter
        with:
          filters: |
            src:
              - 'src/signedsource-rs/**'
              - 'src/abacus/**'

      # https://github.com/actions-rs/toolchain
      - uses: actions-rs/toolchain@v1.0.7
        if: steps.paths-filter.outputs.src == 'true'
        with:
          profile: minimal
          components: clippy
          toolchain: 1.53.0
          override: true
          target: ${{ matrix.target }}

      # https://github.com/actions-rs/cargo
      - uses: actions-rs/cargo@v1.0.3
        if: steps.paths-filter.outputs.src == 'true'
        with:
          command: clippy
          # `--all-targets` + `--all-features`   (in order to also check tests and non-default crate features)
          args: >-
            --locked
            --all-targets
            --all-features
            --manifest-path ${{ matrix.manifest }}
            --target ${{ matrix.target }}

      # https://github.com/actions-rs/cargo
      - name: Run all tests
        uses: actions-rs/cargo@v1.0.3
        if: steps.paths-filter.outputs.src == 'true'
        with:
          command: test
          args: >-
            --no-fail-fast
            --manifest-path ${{ matrix.manifest }}
            --target ${{ matrix.target }}
            --color always

      # https://github.com/actions-rs/cargo
      # TODO: replace with `--include-ignored` once it's in stable Rust Compiler
      # TODO: how to run integration tests better? (they have extra platform requirements)
      # - name: Run all IGNORED tests
      #   uses: actions-rs/cargo@v1.0.3
      #   with:
      #     command: test
      #     args: >-
      #       --no-fail-fast
      #       --manifest-path ${{ matrix.manifest }}
      #       --target ${{ matrix.target }}
      #       -- --ignored
