name: Daily Rust Cargo update

on:
  workflow_dispatch:
  schedule:
    # daily (https://crontab.guru/#0_5_*_*_*)
    - cron: '0 5 * * *'

jobs:
  daily-cargo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - 'src/abacus/Cargo.toml'
          - 'src/x/Cargo.toml'

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3.0.2

      # https://github.com/actions-rs/toolchain
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      # https://github.com/actions-rs/cargo
      - name: Run cargo-update
        uses: actions-rs/cargo@v1.0.3
        with:
          command: update
          args: >-
            --manifest-path ${{ matrix.manifest }}
            --color always

      # https://github.com/peter-evans/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Daily Rust Cargo update (${{ matrix.manifest }})'
          title: 'Daily Rust Cargo update (${{ matrix.manifest }})'
          delete-branch: true
          branch-suffix: random
          labels: |
            dependencies
