name: Dockerfile Builder

on:
  push:
    branches:
      - master

jobs:
  # https://docs.docker.com/ci-cd/github-actions/
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        project:
          - 'abacus'
          - 'abacus-backoffice'
          - 'abacus-kochka'
        include:
          - project: abacus
            projectPath: './src/abacus'
            projectGlob: './src/abacus/**'
            projectDockerfile: './src/abacus/Dockerfile'
            projectImageName: 'adeira/abacus'
          - project: abacus-backoffice
            projectPath: './src/abacus-backoffice'
            projectGlob: './src/abacus-backoffice/**'
            projectDockerfile: './src/abacus-backoffice/Dockerfile'
            projectImageName: 'adeira/abacus-backoffice'
          - project: abacus-kochka
            projectPath: './src/abacus-kochka'
            projectGlob: './src/abacus-kochka/**'
            projectDockerfile: './src/abacus-kochka/Dockerfile'
            projectImageName: 'adeira/abacus-kochka'

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2.4.0
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            src:
              - ${{ matrix.projectGlob }}

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        if: steps.changes.outputs.src == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      # https://github.com/docker/metadata-action
      - name: Collect Docker metadata
        if: steps.changes.outputs.src == 'true'
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ matrix.projectImageName }}
          flavor: |
            latest=true
          tags: |
            type=sha

      # https://github.com/docker/build-push-action
      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: ${{ matrix.projectPath }}
          file: ${{ matrix.projectDockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        if: steps.changes.outputs.src == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
