name: Dockerfile Builder

on:
  push:
    branches:
      - master

jobs:
  # https://docs.docker.com/ci-cd/github-actions/
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        project:
          - 'abacus'
        include:
          - project: abacus
            projectPath: './src/abacus'
            projectGlob: './src/abacus/**'
            projectDockerfile: './src/abacus/Dockerfile'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - uses: dorny/paths-filter@v2.10.1
        id: changes
        with:
          filters: |
            src:
              - ${{ matrix.projectGlob }}

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        if: steps.changes.outputs.src == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0

      # https://github.com/docker/build-push-action
      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: ${{ matrix.projectPath }}
          file: ${{ matrix.projectDockerfile }}
          push: true
          tags: adeira/abacus:latest # TODO: include in the build matrix

      - name: Image digest
        if: steps.changes.outputs.src == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
