# https://github.com/marketplace/actions/merge-pal
name: Merge Pal (events)

on:
  push: {} # update PR when base branch is updated
  status: {} # try to merge when other checks are completed
  pull_request_review: # try to merge after review
    types:
      - submitted
      - edited
      - dismissed
  pull_request: # try to merge if labels have changed (white/black list)
    types:
      - labeled
      - unlabeled

env:
  CI: true
  FORCE_COLOR: '1' # https://github.com/chalk/chalk/issues/203

jobs:
  # that's all, single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
