# Please note: some ecosystems are supported by default
# https://docs.github.com/en/free-pro-team@latest/github/visualizing-repository-data-with-graphs/about-the-dependency-graph#supported-package-ecosystems

name: Security audit

on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │    ┌───────────── day of the month (1 - 31)
    #        │ │    │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │    │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │    │ │ │
    #        │ │    │ │ │
    #        │ │    │ │ │
    - cron: '0 0,12 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
