name: Weekly Rust Cargo update

on:
  workflow_dispatch:
  schedule:
    # weekly "at 05:00 on Monday" (https://crontab.guru/#0_5_*_*_1)
    - cron: '0 5 * * 1'

jobs:
  weekly-cargo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        manifest:
          - 'src/abacus/Cargo.toml'
          - 'src/x/Cargo.toml'

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3.5.2

      # https://github.com/dtolnay/rust-toolchain
      - uses: dtolnay/rust-toolchain@stable

      # Cargo update
      - run: cargo update --manifest-path ${{ matrix.manifest }} --color always

      # https://github.com/peter-evans/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Weekly Rust Cargo update (${{ matrix.manifest }})'
          title: 'Weekly Rust Cargo update (${{ matrix.manifest }})'
          delete-branch: true
          branch-suffix: random
          labels: |
            dependencies
